"""add category created_at

Revision ID: 66107800329f
Revises: 721e32875e20
Create Date: 2026-09-15 15:55:54.752245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66107800329f'
down_revision = '721e32875e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
