"""add document description

Revision ID: 721e32875e20
Revises: 6c07f889c867
Create Date: 2026-09-15 09:39:52.348995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721e32875e20'
down_revision = '6c07f889c867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
