# Generated by Django 6.1.1 on 2026-09-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="description",
            field=models.CharField(default="", max_length=500),
        ),
    ]
